<a href="https://colab.research.google.com/github/JYLeem/LA02/blob/main/%5B00%5D%EC%8B%A4%EC%8A%B5Zero.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [8]:
def print_val(x):
  print("Type: ", type(x))
  print("Shape", x.shape)
  print("값 \n", x)
  print(" ")

**rank 1 np array**

In [11]:
x = np.array([1,2,3])
print_val(x)

x[0] = 5
print_val(x)

Type:  <class 'numpy.ndarray'>
Shape (3,)
값 
 [1 2 3]
 
Type:  <class 'numpy.ndarray'>
Shape (3,)
값 
 [5 2 3]
 


**rank 2 np array**

In [14]:
y = np.array([[1,2,3], [4,5,6]])
print_val(y)

Type:  <class 'numpy.ndarray'>
Shape (2, 3)
값 
 [[1 2 3]
 [4 5 6]]
 


In [16]:
a = np.zeros((2,2))
print_val(a)

Type:  <class 'numpy.ndarray'>
Shape (2, 2)
값 
 [[0. 0.]
 [0. 0.]]
 
